package pojos;
// Generated Dec 9, 2018 2:24:07 PM by Hibernate Tools 4.3.1



/**
 * JaringanEks generated by hbm2java
 */
public class JaringanEks  implements java.io.Serializable {


     private String idjaringan;
     private String lat;
     private String long_;
     private String powerSinyal;

    public JaringanEks() {
    }

	
    public JaringanEks(String idjaringan) {
        this.idjaringan = idjaringan;
    }
    public JaringanEks(String idjaringan, String lat, String long_, String powerSinyal) {
       this.idjaringan = idjaringan;
       this.lat = lat;
       this.long_ = long_;
       this.powerSinyal = powerSinyal;
    }
   
    public String getIdjaringan() {
        return this.idjaringan;
    }
    
    public void setIdjaringan(String idjaringan) {
        this.idjaringan = idjaringan;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getLong_() {
        return this.long_;
    }
    
    public void setLong_(String long_) {
        this.long_ = long_;
    }
    public String getPowerSinyal() {
        return this.powerSinyal;
    }
    
    public void setPowerSinyal(String powerSinyal) {
        this.powerSinyal = powerSinyal;
    }




}


