package pojos;
// Generated Dec 4, 2018 9:17:33 AM by Hibernate Tools 4.3.1



/**
 * JaringanEks generated by hbm2java
 */
public class JaringanEks  implements java.io.Serializable {


     private String idEksisting;
     private Double coverageArea;
     private String namaBts;
     private Integer jumlahBts;
     private Double kekuatanSinyal;

    public JaringanEks() {
    }

	
    public JaringanEks(String idEksisting) {
        this.idEksisting = idEksisting;
    }
    public JaringanEks(String idEksisting, Double coverageArea, String namaBts, Integer jumlahBts, Double kekuatanSinyal) {
       this.idEksisting = idEksisting;
       this.coverageArea = coverageArea;
       this.namaBts = namaBts;
       this.jumlahBts = jumlahBts;
       this.kekuatanSinyal = kekuatanSinyal;
    }
   
    public String getIdEksisting() {
        return this.idEksisting;
    }
    
    public void setIdEksisting(String idEksisting) {
        this.idEksisting = idEksisting;
    }
    public Double getCoverageArea() {
        return this.coverageArea;
    }
    
    public void setCoverageArea(Double coverageArea) {
        this.coverageArea = coverageArea;
    }
    public String getNamaBts() {
        return this.namaBts;
    }
    
    public void setNamaBts(String namaBts) {
        this.namaBts = namaBts;
    }
    public Integer getJumlahBts() {
        return this.jumlahBts;
    }
    
    public void setJumlahBts(Integer jumlahBts) {
        this.jumlahBts = jumlahBts;
    }
    public Double getKekuatanSinyal() {
        return this.kekuatanSinyal;
    }
    
    public void setKekuatanSinyal(Double kekuatanSinyal) {
        this.kekuatanSinyal = kekuatanSinyal;
    }




}


