package pojos;
// Generated Dec 4, 2018 1:06:35 PM by Hibernate Tools 4.3.1



/**
 * LokasiDesa generated by hbm2java
 */
public class LokasiDesa  implements java.io.Serializable {


     private long idDesa;
     private Double lat;
     private Double log;
     private Double jumPenduduk;

    public LokasiDesa() {
    }

	
    public LokasiDesa(long idDesa) {
        this.idDesa = idDesa;
    }
    public LokasiDesa(long idDesa, Double lat, Double log, Double jumPenduduk) {
       this.idDesa = idDesa;
       this.lat = lat;
       this.log = log;
       this.jumPenduduk = jumPenduduk;
    }
   
    public long getIdDesa() {
        return this.idDesa;
    }
    
    public void setIdDesa(long idDesa) {
        this.idDesa = idDesa;
    }
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    public Double getLog() {
        return this.log;
    }
    
    public void setLog(Double log) {
        this.log = log;
    }
    public Double getJumPenduduk() {
        return this.jumPenduduk;
    }
    
    public void setJumPenduduk(Double jumPenduduk) {
        this.jumPenduduk = jumPenduduk;
    }




}


