package pojos;
// Generated Dec 4, 2018 9:17:33 AM by Hibernate Tools 4.3.1



/**
 * LokasiKampung generated by hbm2java
 */
public class LokasiKampung  implements java.io.Serializable {


     private String idLokasi;
     private String namaKampung;
     private Double luasLokasi;
     private Integer jarakToBts;

    public LokasiKampung() {
    }

	
    public LokasiKampung(String idLokasi) {
        this.idLokasi = idLokasi;
    }
    public LokasiKampung(String idLokasi, String namaKampung, Double luasLokasi, Integer jarakToBts) {
       this.idLokasi = idLokasi;
       this.namaKampung = namaKampung;
       this.luasLokasi = luasLokasi;
       this.jarakToBts = jarakToBts;
    }
   
    public String getIdLokasi() {
        return this.idLokasi;
    }
    
    public void setIdLokasi(String idLokasi) {
        this.idLokasi = idLokasi;
    }
    public String getNamaKampung() {
        return this.namaKampung;
    }
    
    public void setNamaKampung(String namaKampung) {
        this.namaKampung = namaKampung;
    }
    public Double getLuasLokasi() {
        return this.luasLokasi;
    }
    
    public void setLuasLokasi(Double luasLokasi) {
        this.luasLokasi = luasLokasi;
    }
    public Integer getJarakToBts() {
        return this.jarakToBts;
    }
    
    public void setJarakToBts(Integer jarakToBts) {
        this.jarakToBts = jarakToBts;
    }




}


