package pojos;
// Generated Dec 4, 2018 9:17:33 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String nama;
     private String password;

    public User() {
    }

	
    public User(String nama) {
        this.nama = nama;
    }
    public User(String nama, String password) {
       this.nama = nama;
       this.password = password;
    }
   
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


