package pojos;
// Generated Nov 28, 2018 5:37:22 PM by Hibernate Tools 4.3.1



/**
 * JaringanEks generated by hbm2java
 */
public class JaringanEks  implements java.io.Serializable {


     private String idBts;
     private String kekuatanSinyal;
     private String coverageArea;

    public JaringanEks() {
    }

	
    public JaringanEks(String idBts) {
        this.idBts = idBts;
    }
    public JaringanEks(String idBts, String kekuatanSinyal, String coverageArea) {
       this.idBts = idBts;
       this.kekuatanSinyal = kekuatanSinyal;
       this.coverageArea = coverageArea;
    }
   
    public String getIdBts() {
        return this.idBts;
    }
    
    public void setIdBts(String idBts) {
        this.idBts = idBts;
    }
    public String getKekuatanSinyal() {
        return this.kekuatanSinyal;
    }
    
    public void setKekuatanSinyal(String kekuatanSinyal) {
        this.kekuatanSinyal = kekuatanSinyal;
    }
    public String getCoverageArea() {
        return this.coverageArea;
    }
    
    public void setCoverageArea(String coverageArea) {
        this.coverageArea = coverageArea;
    }




}


